apiVersion: v1
kind: Service
metadata:
  name: flask-microservice-service
  labels:
    app: flask-microservice
spec:
  type: LoadBalancer
  selector:
    app: flask-microservice
  ports:
    - name: http          # <-- added
      protocol: TCP
      port: 80
      targetPort: 5000
