grafana:
  adminPassword: "${GRAFANA_ADMIN_PASSWORD}"   # <-- uppercase to match workflow
  service:
    type: LoadBalancer
  persistence:
    enabled: false

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false   # <-- correct key
  service:
    type: LoadBalancer

alertmanager:
  enabled: false

prometheusOperator:
  resources:
    requests:
      cpu: 100m
      memory: 200Mi
  admissionWebhooks:
    enabled: true
